"""CSS animation injection for animated heatmaps."""

from __future__ import annotations

import hashlib
import math
from collections.abc import Sequence
from numbers import Real
from typing import Literal

from lxml import etree

from pathy_svg._constants import SVG_NS, local_tag
from pathy_svg._constants import (
    rendered_colorable_elements as _rendered_colorable_elements,
)

AnimationEffect = Literal["pulse", "fade_in", "blink", "sequential"]

_ANIMATION_EFFECTS = frozenset({"pulse", "fade_in", "blink", "sequential"})
_GENERATED_STYLE_ATTR = "data-pathy-animation"
_GENERATED_CLASS_ATTR = "data-pathy-animation-class"
_GENERATED_CLASS_BASE = "pathy-animation-target"
_PRIVATE_NS = "urn:pathy-svg:private:animation:v1"
_PROVENANCE_ATTR = f"{{{_PRIVATE_NS}}}provenance"
_PROVENANCE_VALUE = "pathy-generated-animation-v1"
_PRIVATE_EFFECT_ATTR = f"{{{_PRIVATE_NS}}}effect"
_PRIVATE_KEYFRAME_ATTR = f"{{{_PRIVATE_NS}}}keyframe"
_PRIVATE_CLASS_ATTR = f"{{{_PRIVATE_NS}}}target-class"
_PRIVATE_CLASS_MARKER_ATTR = f"{{{_PRIVATE_NS}}}class-marker"
_KEYFRAME_BASES = {
    "pulse": "pathy-pulse",
    "fade_in": "pathy-fade",
    "blink": "pathy-blink",
    "sequential": "pathy-seq",
}


def _css_string(value: str) -> str:
    """Escape a value for use inside a double-quoted CSS string."""
    return "".join(
        char
        if char.isascii() and (char.isalnum() or char in "_-")
        else f"\\{ord(char):x} "
        for char in value
    )


def _normalise_data_order(data_order: Sequence[str]) -> list[str]:
    if isinstance(data_order, (str, bytes)) or not isinstance(data_order, Sequence):
        raise TypeError("data_order must be a sequence of element ID strings")
    if any(not isinstance(eid, str) for eid in data_order):
        raise TypeError("data_order must be a sequence of element ID strings")
    return list(dict.fromkeys(data_order))


def _generated_name(name: str, base: str) -> bool:
    """Return whether *name* is *base* or its canonical suffix >= 2."""
    if name == base:
        return True
    prefix = f"{base}-"
    if not name.startswith(prefix):
        return False
    suffix = name[len(prefix) :]
    return (
        suffix.isascii()
        and suffix.isdecimal()
        and not suffix.startswith("0")
        and int(suffix) >= 2
    )


def _colorable_ids(root: etree._Element) -> list[str]:
    """Return rendered colorable IDs in document order, without duplicates."""
    ids = (element.get("id") for element in _rendered_colorable_elements(root))
    return list(dict.fromkeys(eid for eid in ids if eid))


def _remove_generated_class(
    root: etree._Element, class_name: str, marker_name: str
) -> None:
    """Remove a class token previously appended by this module."""
    marker_attr = f"{{{_PRIVATE_NS}}}{marker_name}"
    suffix = f" {class_name}"
    for element in root.iter():
        if element.get(marker_attr) != class_name:
            continue
        class_value = element.get("class")
        if class_value == class_name:
            del element.attrib["class"]
        elif class_value is not None and class_value.endswith(suffix):
            element.set("class", class_value[: -len(suffix)])
        element.attrib.pop(marker_attr, None)


def _owned_generated_style(style: etree._Element) -> bool:
    """Recognize only styles carrying the complete private ownership schema."""
    if style.tag != f"{{{SVG_NS}}}style":
        return False
    if style.get(_GENERATED_STYLE_ATTR) != "true":
        return False
    if style.get(_PROVENANCE_ATTR) != _PROVENANCE_VALUE:
        return False

    effect = style.get(_PRIVATE_EFFECT_ATTR)
    keyframe_name = style.get(_PRIVATE_KEYFRAME_ATTR)
    css = style.text or ""
    if effect not in _ANIMATION_EFFECTS or not keyframe_name:
        return False
    keyframe_base = f"{_KEYFRAME_BASES[effect]}-"
    if not (
        keyframe_name.startswith(keyframe_base)
        or f"--keyframe--{keyframe_base}" in keyframe_name
    ):
        return False
    if f"@keyframes {keyframe_name} " not in css:
        return False
    if effect != "sequential" and f"animation: {keyframe_name} " not in css:
        return False

    target_class = style.get(_PRIVATE_CLASS_ATTR)
    public_target_class = style.get(_GENERATED_CLASS_ATTR)
    marker_name = style.get(_PRIVATE_CLASS_MARKER_ATTR)
    if effect == "sequential":
        return (
            target_class is None and public_target_class is None and marker_name is None
        )
    return bool(
        target_class
        and target_class == public_target_class
        and _generated_name(target_class, _GENERATED_CLASS_BASE)
        and marker_name
        and _generated_name(marker_name, "class-owner")
    )


def _remove_generated_styles(root: etree._Element) -> None:
    """Remove animation styles previously generated by this module."""
    generated_classes: set[tuple[str, str]] = set()
    for style in list(root.iter()):
        if _owned_generated_style(style):
            class_name = style.get(_PRIVATE_CLASS_ATTR)
            marker_name = style.get(_PRIVATE_CLASS_MARKER_ATTR)
            if class_name and marker_name:
                generated_classes.add((class_name, marker_name))
            parent = style.getparent()
            if parent is not None:
                parent.remove(style)
    for class_name, marker_name in generated_classes:
        _remove_generated_class(root, class_name, marker_name)


def _unique_class_marker(root: etree._Element) -> str:
    used = {
        attr_name.split("}", 1)[1]
        for element in root.iter()
        for attr_name in element.attrib
        if attr_name.startswith(f"{{{_PRIVATE_NS}}}")
    }
    marker_name = "class-owner"
    suffix = 2
    while marker_name in used:
        marker_name = f"class-owner-{suffix}"
        suffix += 1
    return marker_name


def _add_generated_class(
    root: etree._Element, elements: Sequence[etree._Element]
) -> tuple[str, str]:
    """Append a collision-free internal class to *elements*."""
    existing_classes = {
        class_name
        for element in root.iter()
        for class_name in (element.get("class") or "").split()
    }
    class_name = _GENERATED_CLASS_BASE
    suffix = 2
    while class_name in existing_classes:
        class_name = f"{_GENERATED_CLASS_BASE}-{suffix}"
        suffix += 1

    marker_name = _unique_class_marker(root)
    marker_attr = f"{{{_PRIVATE_NS}}}{marker_name}"
    for element in elements:
        class_value = element.get("class")
        element.set(
            "class", f"{class_value} {class_name}" if class_value else class_name
        )
        element.set(marker_attr, class_name)
    return class_name, marker_name


def _unique_keyframe_name(root: etree._Element, effect: AnimationEffect) -> str:
    """Build a stable, document-specific keyframe name."""
    user_css = "\0".join(
        element.text or ""
        for element in root.iter()
        if local_tag(element.tag) == "style"
    )
    digest = hashlib.sha256(user_css.encode()).hexdigest()[:12]
    return f"{_KEYFRAME_BASES[effect]}-{digest}"


def _add_style(
    defs: etree._Element,
    css: str,
    *,
    effect: AnimationEffect,
    keyframe_name: str,
    target_class: str | None = None,
    class_marker: str | None = None,
) -> None:
    style = etree.SubElement(defs, f"{{{SVG_NS}}}style")
    style.set(_GENERATED_STYLE_ATTR, "true")
    style.set(_PROVENANCE_ATTR, _PROVENANCE_VALUE)
    style.set(_PRIVATE_EFFECT_ATTR, effect)
    style.set(_PRIVATE_KEYFRAME_ATTR, keyframe_name)
    if target_class is not None:
        style.set(_GENERATED_CLASS_ATTR, target_class)
        style.set(_PRIVATE_CLASS_ATTR, target_class)
    if class_marker is not None:
        style.set(_PRIVATE_CLASS_MARKER_ATTR, class_marker)
    style.text = css


def inject_animation(
    tree: etree._ElementTree,
    *,
    effect: AnimationEffect = "pulse",
    duration: float = 2.0,
    loop: bool = True,
    data_order: Sequence[str] | None = None,
) -> None:
    """Inject CSS keyframe animations into the SVG. Modifies tree in-place.

    Effects:
        - "pulse": Scale up and down
        - "fade_in": Fade from transparent to opaque
        - "sequential": Appear one by one in order
        - "blink": Toggle visibility

    For the sequential effect, ``data_order`` controls the stagger order. When
    omitted, IDs on colorable elements are discovered in document order.
    Colorable elements without IDs are left unchanged.
    """
    if not isinstance(effect, str):
        raise TypeError("Animation effect must be a string")
    if effect not in _ANIMATION_EFFECTS:
        raise ValueError(f"Unknown animation effect: {effect!r}")
    if not isinstance(duration, Real):
        raise TypeError("Animation duration must be a real number")
    if isinstance(duration, bool):
        raise TypeError("Animation duration must be a real number")
    try:
        duration_value = float(duration)
    except OverflowError:
        raise ValueError(
            "Animation duration must be a finite number greater than 0"
        ) from None
    if not math.isfinite(duration_value) or duration_value <= 0:
        raise ValueError("Animation duration must be a finite number greater than 0")
    if not isinstance(loop, bool):
        raise TypeError("Animation loop must be a boolean")
    explicit_order = (
        _normalise_data_order(data_order)
        if effect == "sequential" and data_order is not None
        else None
    )

    root = tree.getroot()
    _remove_generated_styles(root)
    keyframe_name = _unique_keyframe_name(root, effect)

    # Find or create <defs>
    defs = root.find(f"{{{SVG_NS}}}defs")
    if defs is None:
        defs = etree.SubElement(root, f"{{{SVG_NS}}}defs")
        root.insert(0, defs)

    iteration = "infinite" if loop else "1"

    if effect == "pulse":
        keyframes = (
            f"@keyframes {keyframe_name} {{"
            "  0%, 100% { transform: scale(1); transform-origin: center; }"
            "  50% { transform: scale(1.05); transform-origin: center; }"
            "}"
        )
        rule = f"animation: {keyframe_name} {duration_value}s ease-in-out {iteration};"

    elif effect == "fade_in":
        keyframes = (
            f"@keyframes {keyframe_name} {{"
            "  0% { opacity: 0; }  100% { opacity: 1; }}"
        )
        rule = f"animation: {keyframe_name} {duration_value}s ease-in {iteration};"

    elif effect == "blink":
        keyframes = (
            f"@keyframes {keyframe_name} {{"
            "  0%, 100% { opacity: 1; }  50% { opacity: 0.2; }}"
        )
        rule = f"animation: {keyframe_name} {duration_value}s step-start {iteration};"

    elif effect == "sequential":
        ordered_ids = _colorable_ids(root) if explicit_order is None else explicit_order
        keyframes = (
            f"@keyframes {keyframe_name} {{"
            "  0% { opacity: 0; }"
            "  10% { opacity: 1; }"
            "  100% { opacity: 1; }"
            "}"
        )
        css_parts = [keyframes]
        count = len(ordered_ids)
        for index, eid in enumerate(ordered_ids):
            delay = (index / count) * duration_value
            css_parts.append(
                f'[id="{_css_string(eid)}"] {{ '
                f"animation: {keyframe_name} {duration_value}s ease-in {iteration}; "
                f"animation-delay: {delay:.2f}s; animation-fill-mode: backwards; }}"
            )
        _add_style(
            defs,
            "\n".join(css_parts),
            effect=effect,
            keyframe_name=keyframe_name,
        )
        return

    target_class, class_marker = _add_generated_class(
        root, _rendered_colorable_elements(root)
    )
    css = f"{keyframes}\n.{target_class} {{ {rule} }}"
    _add_style(
        defs,
        css,
        effect=effect,
        keyframe_name=keyframe_name,
        target_class=target_class,
        class_marker=class_marker,
    )
